global using Domain.Entities.Departments;
global using Domain.Entities.JobLevels;
global using Domain.Entities.Notifications;
global using Domain.Entities.Roles;
global using Domain.Entities.Users;
global using Domain.Enums.JobLevels;
global using Domain.Enums.Notifications;
global using Domain.Enums.Roles;
global using Domain.Enums.Users;
