global using API;
global using Domain;
global using Application;
global using Infrastructure;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.SignalR;
global using System.Security.Claims;
global using Microsoft.AspNetCore.Mvc.Filters;
